#version: '3.3'
#docker network create -d bridge backend
services:
  database-movie:
    image: postgres:16-alpine
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "movie" #database name
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - /D/PostgreSQL/16/movie/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "database-movie" #ip address in docker

  database-person:
    image: postgres:16-alpine
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "person"
      PGDATA: /var/lib/postgresql/data
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
#      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - /D/PostgreSQL/16/person/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "database-person"
#
#docker network create -d bridge backend
#services:
#  config-server:
#    image: localhost:5000/spring-cloud-config-server:1.0-SNAPSHOT
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    networks:
#      backend:
#        aliases:
#          - "config-server"

  naming-server:
    image: oraylean/naming-server:latest
    container_name: naming-server
    environment:
      - "SPRING_PROFILES_ACTIVE=cloud"
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "naming-serve"

  gateway-server:
    image: oraylean/api-gateway:latest
    container_name: api-gateway-server
    environment:
      - "SPRING_PROFILES_ACTIVE=cloud"
    ports:
      - "8765:8765"
    depends_on:
      config-server:
        condition: service_started
      naming-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "api-gateway-server"


  movie-service-1:
    image: oraylean/movie-service:latest
    container_name: movie-service-1
    environment:
      SERVER_PORT: 8100
      SPRING_PROFILES_ACTIVE: "cloud"
    ports:
      - "8100:8100"
    networks:
      - backend

  movie-service-2:
    image: oraylean/movie-service:latest
    container_name: movie-service-2
    environment:
      SERVER_PORT: 8101
      SPRING_PROFILES_ACTIVE: "cloud"
    ports:
      - "8101:8101"
    networks:
      - backend

  person-service-1:
    image: oraylean/person-service:latest
    container_name: person-service-1
    environment:
      SERVER_PORT: 8000
      SPRING_PROFILES_ACTIVE: "cloud"
    ports:
      - "8000:8000"
    networks:
      - backend

  person-service-2:
    image: oraylean/person-service:latest
    container_name: person-service-2
    environment:
      SERVER_PORT: 8001
      SPRING_PROFILES_ACTIVE: "cloud"
    ports:
      - "8001:8001"
    networks:
      - backend

networks:
  backend:
    driver: bridge